name: SmokeTest

on: [push]

jobs:
  smoke-test:
    strategy:
      matrix:
        go:
          - 1.15

    name: SmokeTest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Add hosts
        run: sudo make add-hosts

      - name: Start servers
        run: make upd

      - name: Run test
        run: make test
